### ISSUE TITLE
i-PRO Maximizer service does not start when PC is restarted

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#16]
@EricBourque  @alexnaicuorbnet 
Test version : v0.9.84

We use  2 PC and restart PC about 5 times in total.
Every time, i-PRO Maximizer service does not start automatically though "Automatic" is set for "Startup Type "

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/e0891c7f-d0a0-407e-8e0e-fc52b6cb9dc3)

From my experience, not "Automatic" but "Automatic(Delayed Start)" may solve this.

**Comment by EricBourque** [comment]
Hi Yohan,

Something must be preventing the service from starting when Milestone is not online yet.
You can set it to delayed start until we (possibly) resolve.
Please also test what happens when i-PRO Maximizer is started, and you restart the Management Server Service.
Please also check the Windows Event Viewer if you can see some information about the service crash:

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/65533203/499a09d0-1882-438f-826f-07df5b52a451)

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque @alexnaicuorbnet 
We tried to change to "Automatic(Delayed Start)"  manually and tested again , it is no problem.
Could you change your installer so that "Automatic(Delayed Start)" is set as default ?

We checked Event Viewer but no error logs.
When we restart Management Server Service, i-PRO Maximizer continues to work well and no Event viewer error log.

**Comment by alexnaicuorbnet** [comment]
For 0.9.85 I didn't change the startup to automatic delayed, but I made some changes to the start method so it starts as fast as possible. If this still doesn't solve the issue I will change the startup to automatic delayed for 1.0.0.

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thank you updating but not fixed in v0.9.85.

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v1.0.0
